

collections:
  letras_disco2:
    title: A Arte de não fazer sentido # Needed for Siteleaf
    output: true
    order:
      - Ficha Técnica.md
      - 31 de janeiro.md
      - Pra quem o sol nasce.md
      - Maconha.md
      - Davi e Golias.md
      - A arte de não fazer sentido.md
      - Minas Gerais.md
      - 1811.md
      - Se não gosta de mim.md
      - Zé Qualquer.md
      - 15 segundos.md
  letras_disco1:
    title: Proibido atirar nos músicos # Needed for Siteleaf
    output: true
    order:
      - Ficha Técnica.md
      - Homofobia É Vômito no Chão.md
      - Help Brazil.md
      - Bacurau.md
      - Homens de Bem.md
      - Alegria.md
      - Porra Deus!.md
      - Drogaria.md
      - Preto no Branco.md
      - Nunca Vai Entrar.md
      - Velho, Feio e Sem Clichê.md
      - Cuzão.md
      - Mão na Cara.md
      - Eu Me Demito.md

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: pt-BR # Set the site language
title: "Antifas!" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logos/Antifas.svg" # Site logo, also used in jekyll-seo-tag
description: "Antifas! " # Site description and default description, also used in jekyll-seo-tag
url: "https://antifas.com.br" # Site url, also used in jekyll-seo-tag
baseurl: ""
css_inline: true 

plugins:
- jekyll-seo-tag

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/logos/Antifas@16px.png'
  32: '/assets/logos/Antifas@32px.png'
  96: '/assets/logos/Antifas@96px.png'
  120: '/assets/logos/Antifas@120px.png'
  144: '/assets/logos/Antifas@144px.png'
  180: '/assets/logos/Antifas@180px.png'
  512: '/assets/logos/Antifas@512px.png'
  1024: '/assets/logos/Antifas@1024px.png'

# 9. Site navigation
navigation_header:
- title: Início
  url: /
- title: Músicas
  url: /musicas.html
- title: Release
  url: /release.html
- title: Contato
  url: /contato.html

navigation_footer:
- title: Créditos
  url: /creditos.html

social_links:
  Instagram: https://www.instagram.com/ant1fas/
  Youtube: https://www.youtube.com/@tvantifas4250
  TikTok: https://www.tiktok.com/@antifasband
  Spotify: https://open.spotify.com/intl-pt/artist/0burhqaWUPZLu4BeKD6PKs
  Email: antifasband@gmail.com
  link: https://www.antifas.com.br

exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- .jekyll-cache
